// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wditpvclpvccxtcdegsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkaXRwdmNscHZjY3h0Y2RlZ3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5OTQ4MjYsImV4cCI6MjA1MTU3MDgyNn0.pqjtfPrGGtRDQuQRWRXALzQM3eF7sTea8IZaH6uzHvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);